package mcp

import "encoding/json"

type JSONRPCRequest struct {
	JSONRPC string          `json:"jsonrpc"`
	Method  string          `json:"method"`
	Params  json.RawMessage `json:"params,omitempty"`
	ID      interface{}     `json:"id"`
}

type JSONRPCResponse struct {
	JSONRPC string      `json:"jsonrpc"`
	Result  interface{} `json:"result,omitempty"`
	Error   *RPCError   `json:"error,omitempty"`
	ID      interface{} `json:"id"`
}

type RPCError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Tool struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	InputSchema interface{} `json:"inputSchema"`
}

type ListToolsResult struct {
	Tools []Tool `json:"tools"`
}

func GenerateManifest() ListToolsResult {
	return ListToolsResult{
		Tools: []Tool{
			{
				Name:        "superdaw_start_gpu_inspector",
				Description: "Starts the high-frequency FFT telemetry stream for a specific plugin, targeting a GPU-Accelerated WebGL frontend.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"plugin_id": map[string]interface{}{"type": "string"},
					},
					"required": []string{"plugin_id"},
				},
			},
			{
				Name:        "superdaw_stop_gpu_inspector",
				Description: "Stops the high-frequency FFT telemetry stream.",
				InputSchema: map[string]interface{}{
					"type":       "object",
					"properties": map[string]interface{}{},
				},
			},

			{
				Name:        "superdaw_translate_preset",
				Description: "Translates a VST preset parameter tree from a source synthesizer format into a target format using semantic mapping.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"preset_json":   map[string]interface{}{"type": "string"},
						"target_format": map[string]interface{}{"type": "string"},
					},
					"required": []string{"preset_json", "target_format"},
				},
			},

			{
				Name:        "superdaw_analyze_project",
				Description: "Run the reasoning sidecar to analyze the current DAW project state for mixing and arrangement insights.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"state_dump": map[string]interface{}{"type": "string"},
					},
					"required": []string{"state_dump"},
				},
			},
			{
				Name:        "superdaw_get_suggestions",
				Description: "Retrieve the latest suggestions generated by the in-DAW reasoning sidecar.",
				InputSchema: map[string]interface{}{
					"type":       "object",
					"properties": map[string]interface{}{},
				},
			},

			{
				Name:        "superdaw_session_join",
				Description: "Join a multi-user collaborative studio session.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"user_id": map[string]interface{}{"type": "string"},
						"name":    map[string]interface{}{"type": "string"},
					},
					"required": []string{"user_id", "name"},
				},
			},
			{
				Name:        "superdaw_session_sync",
				Description: "Sync current shared state of the multi-user studio session.",
				InputSchema: map[string]interface{}{
					"type":       "object",
					"properties": map[string]interface{}{},
				},
			},

			{
				Name:        "superdaw_set_mixer",
				Description: "Modify track volume and panning.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"track_id": map[string]interface{}{"type": "string"},
						"volume":   map[string]interface{}{"type": "number"},
						"pan":      map[string]interface{}{"type": "number"},
						"daw":      map[string]interface{}{"type": "string", "enum": []string{"ableton", "reaper", "ardour", "bitwig", "flstudio", "logic", "cubase"}},
					},
					"required": []string{"track_id"},
				},
			},
			{
				Name:        "superdaw_generate_euclidean",
				Description: "Generate a Euclidean rhythm pattern on a target track.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"track_id": map[string]interface{}{"type": "string"},
						"hits":     map[string]interface{}{"type": "integer"},
						"steps":    map[string]interface{}{"type": "integer"},
						"pitch":    map[string]interface{}{"type": "integer"},
						"daw":      map[string]interface{}{"type": "string"},
					},
					"required": []string{"track_id", "hits", "steps"},
				},
			},
			{
				Name:        "superdaw_write_midi",
				Description: "Inject MIDI notes into a clip.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"track_id":   map[string]interface{}{"type": "string"},
						"clip_index": map[string]interface{}{"type": "integer"},
						"notes": map[string]interface{}{
							"type": "array",
							"items": map[string]interface{}{
								"type": "object",
								"properties": map[string]interface{}{
									"pitch":      map[string]interface{}{"type": "integer"},
									"velocity":   map[string]interface{}{"type": "integer"},
									"start_beat": map[string]interface{}{"type": "number"},
									"duration":   map[string]interface{}{"type": "number"},
								},
							},
						},
						"daw": map[string]interface{}{"type": "string"},
					},
					"required": []string{"track_id", "notes"},
				},
			},
			{
				Name:        "superdaw_transport_control",
				Description: "Control transport (play, stop, tempo).",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"playing": map[string]interface{}{"type": "boolean"},
						"bpm":     map[string]interface{}{"type": "number"},
						"daw":     map[string]interface{}{"type": "string"},
					},
				},
			},
			{
				Name:        "superdaw_create_track",
				Description: "Create a new track.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"name": map[string]interface{}{"type": "string"},
						"type": map[string]interface{}{"type": "string", "enum": []string{"audio", "midi"}},
						"daw":  map[string]interface{}{"type": "string"},
					},
					"required": []string{"name", "type"},
				},
			},
			{
				Name:        "superdaw_generate_euclidean",
				Description: "Generate a Euclidean rhythm.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"track_id": map[string]interface{}{"type": "string"},
						"hits":     map[string]interface{}{"type": "integer"},
						"steps":    map[string]interface{}{"type": "integer"},
						"pitch":    map[string]interface{}{"type": "integer"},
						"daw":      map[string]interface{}{"type": "string"},
					},
					"required": []string{"track_id", "hits", "steps", "pitch"},
				},
			},
			{
				Name:        "superdaw_list_clips",
				Description: "List clips on a track.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"track_id": map[string]interface{}{"type": "string"},
						"daw":      map[string]interface{}{"type": "string"},
					},
					"required": []string{"track_id"},
				},
			},
			{
				Name:        "superdaw_delete_clip",
				Description: "Delete a clip.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"track_id": map[string]interface{}{"type": "string"},
						"clip_idx": map[string]interface{}{"type": "integer"},
						"daw":      map[string]interface{}{"type": "string"},
					},
					"required": []string{"track_id", "clip_idx"},
				},
			},
			{
				Name:        "superdaw_list_plugins",
				Description: "List available VST plugins.",
				InputSchema: map[string]interface{}{
					"type":       "object",
					"properties": map[string]interface{}{},
				},
			},
			{
				Name:        "superdaw_get_plugin_params",
				Description: "Get parameters for a specific plugin.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"plugin_name": map[string]interface{}{"type": "string"},
					},
					"required": []string{"plugin_name"},
				},
			},
			{
				Name:        "superdaw_separate_stems",
				Description: "Separate audio into stems using AI (Spleeter).",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"input_path": map[string]interface{}{"type": "string"},
						"output_dir": map[string]interface{}{"type": "string"},
						"stems":      map[string]interface{}{"type": "integer", "default": 4},
					},
					"required": []string{"input_path", "output_dir"},
				},
			},
			{
				Name:        "superdaw_custom_command",
				Description: "Execute a DAW-specific custom command.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"command": map[string]interface{}{"type": "string"},
						"args":    map[string]interface{}{"type": "object"},
						"daw":     map[string]interface{}{"type": "string"},
					},
					"required": []string{"command"},
				},
			},
			{
				Name:        "superdaw_patch_audio",
				Description: "Virtually patch audio between two DAWs.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"source_daw":   map[string]interface{}{"type": "string"},
						"source_track": map[string]interface{}{"type": "string"},
						"dest_daw":     map[string]interface{}{"type": "string"},
						"dest_track":   map[string]interface{}{"type": "string"},
					},
					"required": []string{"source_daw", "source_track", "dest_daw", "dest_track"},
				},
			},
			{
				Name:        "superdaw_unpatch_audio",
				Description: "Remove a virtual audio patch.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"source_daw":   map[string]interface{}{"type": "string"},
						"source_track": map[string]interface{}{"type": "string"},
						"dest_daw":     map[string]interface{}{"type": "string"},
						"dest_track":   map[string]interface{}{"type": "string"},
					},
					"required": []string{"source_daw", "source_track", "dest_daw", "dest_track"},
				},
			},
			{
				Name:        "superdaw_import_generative",
				Description: "Import AI-generated stems from a prompt.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"prompt":     map[string]interface{}{"type": "string"},
						"target_daw": map[string]interface{}{"type": "string"},
					},
					"required": []string{"prompt", "target_daw"},
				},
			},
			{
				Name:        "superdaw_list_generative_jobs",
				Description: "List all active and completed AI generation jobs.",
				InputSchema: map[string]interface{}{
					"type":       "object",
					"properties": map[string]interface{}{},
				},
			},
			{
				Name:        "superdaw_get_tracks",
				Description: "Get a list of tracks and their configurations from the active DAW.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"daw": map[string]interface{}{"type": "string"},
					},
				},
			},
			{
				Name:        "superdaw_get_transport_state",
				Description: "Retrieve the current transport state (playing, bpm) from the DAW.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"daw": map[string]interface{}{"type": "string"},
					},
				},
			},
			{
				Name:        "superdaw_save_session",
				Description: "Save the current studio state (routing, patches) to a file.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"filename": map[string]interface{}{"type": "string", "default": "studio_session.json"},
					},
				},
			},
			{
				Name:        "superdaw_load_session",
				Description: "Load a previously saved studio state from a file.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"filename": map[string]interface{}{"type": "string", "default": "studio_session.json"},
					},
				},
			},
			{
				Name:        "superdaw_generate_music",
				Description: "Generate musical patterns using AI heuristics.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"style":    map[string]interface{}{"type": "string", "enum": []string{"techno", "ambient", "basic"}},
						"bars":     map[string]interface{}{"type": "integer", "default": 4},
						"track_id": map[string]interface{}{"type": "string"},
						"daw":      map[string]interface{}{"type": "string"},
					},
					"required": []string{"style", "track_id"},
				},
			},
			{
				Name:        "superdaw_set_plugin_parameter",
				Description: "Adjust a parameter of a VST plugin by name.",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"plugin_name":    map[string]interface{}{"type": "string"},
						"parameter_name": map[string]interface{}{"type": "string"},
						"value":          map[string]interface{}{"type": "number"},
						"track_id":       map[string]interface{}{"type": "string"},
						"daw":            map[string]interface{}{"type": "string"},
					},
					"required": []string{"plugin_name", "parameter_name", "value", "track_id"},
				},
			},
			{
				Name:        "superdaw_fire_scene",
				Description: "Trigger a session scene (Ableton/Bitwig).",
				InputSchema: map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"scene_index": map[string]interface{}{"type": "integer"},
						"daw":         map[string]interface{}{"type": "string"},
					},
					"required": []string{"scene_index"},
				},
			},
		},
	}
}
